spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://217.160.172.112:5432/poll
    username: admin
    password: tshirt.67
    driver-class-name: org.postgresql.Driver